const User = [
  {
    name: "John Doe",
    username: "johndoe123",
    DOB: "1990-01-01",
    age: 32,
    gender: "male",
    blood_group: "A+",
    contact_number: "+1234567890",
    email: "johndoe@example.com",
    allergies: ["Peanuts", "Penicillin"],
    past_surgeries: ["Appendectomy", "Knee surgery"],
  },
  {
    name: "Jane Smith",
    username: "janesmith456",
    DOB: "1985-05-15",
    age: 37,
    gender: "female",
    blood_group: "B-",
    contact_number: "+1987654321",
    email: "janesmith@example.com",
    allergies: ["Shellfish", "Dust"],
    past_surgeries: ["Hip replacement", "Gallbladder removal"],
  },
  {
    name: "Michael Johnson",
    username: "michaelj89",
    DOB: "1989-08-20",
    age: 33,
    gender: "male",
    blood_group: "O+",
    contact_number: "+1122334455",
    email: "michaelj@example.com",
    allergies: ["Pollen", "Aspirin"],
    past_surgeries: ["Tonsillectomy", "Hernia repair"],
  },
  {
    name: "Emily Davis",
    username: "emilydavis22",
    DOB: "1995-03-10",
    age: 27,
    gender: "female",
    blood_group: "AB-",
    contact_number: "+3344556677",
    email: "emilydavis@example.com",
    allergies: ["Eggs", "Latex"],
    past_surgeries: ["Cataract surgery", "Appendectomy"],
  },
];

// Export the array as a module
export default User;
